import { Rubik } from "next/font/google";
import "./globals.css";
import "react-multi-carousel/lib/styles.css";
import Navbar from "@/sections/Navbar";

const RubikSans = Rubik({
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${RubikSans.className}  antialiased`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
